*** Variables ***
${NAME_TEXT_FIELD}                     id: register-name
${EMAIL_TEXT_FIELD}                    id: register-mail
${PASS_TEXT_FIELD}                     id: register-pass
${CONFIRM_PASS_TEXT_FIELD}             id: register-confirm-pass
${BUSINESS_ENTITY_COMBOBOX}            id: register-user-type
${TERMS_OF_USE_CHECKBOX}               id: terms-of-use
${REGISTER_BUTTON}                     //input[@id="submit-register"]